namespace U4DosRandomizer
{
    public interface IAvatarOffset
    {
        int MOONGATE_X_OFFSET { get; }
        int MOONGATE_Y_OFFSET { get; }
        int AREA_X_OFFSET { get; }
        int AREA_Y_OFFSET { get; }
        int LOC_BUILDINGS { get; }
        int LOC_CASTLES { get; }
        int LOC_LCB { get; }
        int LOC_LYCAEUM { get; }
        int LOC_EMPATH { get; }
        int LOC_SERPENT { get; }
        int LOC_TOWNS { get; }
        int LOC_MOONGLOW { get; }
        int LOC_BRITAIN { get; }
        int LOC_JHELOM { get; }
        int LOC_YEW { get; }
        int LOC_MINOC { get; }
        int LOC_TRINSIC { get; }
        int LOC_SKARA { get; }
        int LOC_MAGINCIA { get; }
        int LOC_PAWS { get; }
        int LOC_DEN { get; }
        int LOC_VESPER { get; }
        int LOC_COVE { get; }
        int LOC_DUNGEONS { get; }
        int LOC_DECEIT { get; }
        int LOC_DESPISE { get; }
        int LOC_DESTARD { get; }
        int LOC_WRONG { get; }
        int LOC_COVETOUS { get; }
        int LOC_SHAME { get; }
        int LOC_HYTHLOTH { get; }
        int LOC_ABYSS { get; }
        int LOC_SHRINES { get; }
        int LOC_HONESTY { get; }
        int LOC_COMPASSION { get; }
        int LOC_VALOR { get; }
        int LOC_JUSTICE { get; }
        int LOC_SACRIFICE { get; }
        int LOC_HONOR { get; }
        int LOC_SPIRITUALITY { get; }
        int LOC_HUMILITY { get; }
        int PIRATE_COVE_X_OFFSET { get; }
        int PIRATE_COVE_Y_OFFSET { get; }
        int PIRATE_COVE_SHIP_TILES { get; }
        int PIRATE_COVE_SPAWN_TRIGGER_Y_OFFSET1 { get; }
        int PIRATE_COVE_SPAWN_TRIGGER_X_OFFSET1 { get; }
        int PIRATE_COVE_SPAWN_TRIGGER_Y_OFFSET2 { get; }
        int PIRATE_COVE_SPAWN_TRIGGER_X_OFFSET2 { get; }
        int MONSTER_HP_OFFSET { get; }
        int MONSTER_LEADER_TYPES_OFFSET { get; }
        int MONSTER_ENCOUNTER_SIZE_OFFSET { get; }
        int ALTAR_EXIT_DESTINATION { get; }
        int AMBUSH_MONSTER_TYPES { get; }
        int CITY_RUNE_MASK_PAIRS_OFFSET { get; }
        int ITEM_LOCATIONS_OFFSET { get; }
        int LB_TEXT_OFFSET { get; }
        int SHRINE_TEXT_OFFSET { get; }
        int WHITE_STONE_LOCATION_TEXT { get; }
        int BLACK_STONE_LOCATION_TEXT { get; }
        int DEMON_SPAWN_TRIGGER_X1_OFFSET { get; }
        int DEMON_SPAWN_TRIGGER_X2_OFFSET { get; }
        int DEMON_SPAWN_TRIGGER_Y1_OFFSET { get; }
        int DEMON_SPAWN_TRIGGER_Y2_OFFSET { get; }
        int DEMON_SPAWN_LOCATION_X_OFFSET { get; }
        int BALLOON_SPAWN_TRIGGER_X_OFFSET { get; }
        int BALLOON_SPAWN_TRIGGER_Y_OFFSET { get; }
        int BALLOON_SPAWN_LOCATION_X_OFFSET { get; }
        int BALLOON_SPAWN_LOCATION_Y_OFFSET { get; }
        int LBC_DUNGEON_EXIT_X_OFFSET { get; }
        int LBC_DUNGEON_EXIT_Y_OFFSET { get; }
        int ITEM_USE_TRIGGER_BELL_X_OFFSET { get; }
        int ITEM_USE_TRIGGER_BELL_Y_OFFSET { get; }
        int ITEM_USE_TRIGGER_BOOK_X_OFFSET { get; }
        int ITEM_USE_TRIGGER_BOOK_Y_OFFSET { get; }
        int ITEM_USE_TRIGGER_CANDLE_X_OFFSET { get; }
        int ITEM_USE_TRIGGER_CANDLE_Y_OFFSET { get; }
        int ITEM_USE_TRIGGER_SKULL_X_OFFSET { get; }
        int ITEM_USE_TRIGGER_SKULL_Y_OFFSET { get; }
        int WHIRLPOOL_EXIT_X_OFFSET { get; }
        int WHIRLPOOL_EXIT_Y_OFFSET { get; }
        int ABYSS_EJECTION_LOCATIONS_X { get; }
        int ABYSS_EJECTION_LOCATIONS_Y { get; }
        int SPELL_RECIPE_OFFSET { get; }
        int BLINK_CAST_EXCLUSION_X1_OFFSET { get; }
        int BLINK_CAST_EXCLUSION_X2_OFFSET { get; }
        int BLINK_CAST_EXCLUSION_Y1_OFFSET { get; }
        int BLINK_CAST_EXCLUSION_Y2_OFFSET { get; }
        int BLINK_DESTINATION_EXCLUSION_X1_OFFSET { get; }
        int BLINK_DESTINATION_EXCLUSION_X2_OFFSET { get; }
        int BLINK_DESTINATION_EXCLUSION_Y1_OFFSET { get; }
        int BLINK_DESTINATION_EXCLUSION_Y2_OFFSET { get; }
        int ENABLE_MIX_QUANTITY_OFFSET { get; }
        int BLINK_DESTINATION2_EXCLUSION_X1_OFFSET { get; }
        int BLINK_DESTINATION2_EXCLUSION_X2_OFFSET { get; }
        int BLINK_DESTINATION2_EXCLUSION_Y1_OFFSET { get; }
        int BLINK_DESTINATION2_EXCLUSION_Y2_OFFSET { get; }
    }
}