name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install dependencies
      run: |
        dotnet restore ./U4DosRandomizer.CLI/U4DosRandomizer.CLI.csproj
        dotnet workload restore ./U4DosRandomizer.UI/U4DosRandomizer.UI.csproj
        dotnet restore ./U4DosRandomizer.UI/U4DosRandomizer.UI.csproj
        dotnet restore ./U4DosRandomizer.UnitTests/U4DosRandomizer.UnitTests.csproj
    - name: Build CLI
      run: dotnet build ./U4DosRandomizer.CLI/U4DosRandomizer.CLI.csproj --configuration Release --no-restore
    - name: Build UI
      run: dotnet build ./U4DosRandomizer.UI/U4DosRandomizer.UI.csproj --configuration Release --no-restore -f:net9.0-windows10.0.19041.0
    - name: Test
      run: dotnet test ./U4DosRandomizer.UnitTests/U4DosRandomizer.UnitTests.csproj --no-restore --verbosity normal
